# Site settings
title: Grizzly && Poppy
description: Modern Front-end Design and Software Engineering
keywords: Software, Web Development && Design
author: Sean Orfila
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
