name:               "SeanBlog"
description:        "Coming soon..."

url:                "https://seandogg.github.io"
author:             "seandogg"
email:              "sean.orfila@gmail.com"
gravatar_hash:      "3ebfff757da27168fb6732a5be9d7b1d"
twitter:            "SeanSince82"
email:              "sean.orfila@gmail.com"
github:             "seandogg"
linkedin:           "sean-orfila"
#facebook:           ""

#disqus_shortname:   ""

background:         "/resources/img/w-5600.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate